name: SpamCop
author: Allogeneous
main: spamcop.SpamCop
version: 1.0.0
description: >
             Advanced anti-spam!



permissions:
    spamCop.canBypassDoubleMessages:
        description: Allows the player to repeat the same message twice in chat
        default: op
    spamCop.canBypassDoubleMessagesTimer:
        description: Allows the player to repeat the same message twice in chat without waiting for the timer
        default: op
    spamCop.canBypassMaxWordLength:
        description: Allows the player to bypass the max letter limet
        default: op
    spamCop.canBypassCharacterPercent:
        description: Allows the player to bypass the character percent check
        default: op
    spamCop.canBypassWordPercent:
        description: Allows the player to bypass the word percent check
        default: op
    spamCop.canBypassSpamKickTimer:
        description: Allows the player to not get kicked for spamming too much
        default: op
    spamCop.canUseCorrections:
        description: Allows the player to use corrections
        default: true
    spamCop.canUseRepeatLetters:
        description: Allows the player to use repeat letters
        default: op
    spamCop.canUseRepeatWords:
        description: Allows the player to use repeat words
        default: op